- name: Set systemd openvpn service name
  set_fact:
    openvpn_service_name: "openvpn@{{openvpn_config_file}}.service"
  when: ansible_service_mgr == "systemd" or (docker_stat_result.stat is defined and docker_stat_result.stat.exists == True)